apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      role: splitter
  template:
    metadata:
      labels:
        role: splitter
    spec:
      containers:
      - name: splitter
        image: marianrap/sdypp_splitter:0.13
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis-service.framework.services.gcp.com.ar."
        - name: REDIS_PWD
          value: "agusmarian"
        - name: RABBIT_HOST
          value: "rabbitmq-service.framework.services.gcp.com.ar."
        - name: RABBIT_USER
          value: "guest"
        - name: RABBIT_PWD
          value: "guest"